apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flightprice

resources:
  - ../../base

patches:
  - path: image-policy-patch.yaml
    target:
      kind: Deployment
      name: flightprice-app
