apiVersion: v1
kind: Service
metadata:
  name: flightprice-app
  labels:
    app: flightprice-app
spec:
  type: ClusterIP
  selector:
    app: flightprice-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
