apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flightprice

resources:
  - namespace.yaml
  - mysql-configmap.yaml
  - mysql-statefulset.yaml
  - app-configmap.yaml
  - logs-pvc.yaml
  - app-deployment.yaml
  - app-service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: flightprice
    includeSelectors: false
